//! The built-in function registry (`cypher-read`, "Expressions and built-in functions").

/// Aggregate function names (lower case).
pub const AGGREGATES: [&str; 10] = [
    "count",
    "sum",
    "avg",
    "min",
    "max",
    "collect",
    "stdev",
    "stdevp",
    "percentilecont",
    "percentiledisc",
];

/// Scalar functions (lower case) that are implemented.
pub const SCALARS: &[&str] = &[
    "id",
    "elementid",
    "labels",
    "type",
    "keys",
    "properties",
    "startnode",
    "endnode",
    "coalesce",
    "size",
    "head",
    "last",
    "tail",
    "range",
    "tostring",
    "tointeger",
    "tofloat",
    "toboolean",
    "tostringornull",
    "tointegerornull",
    "tofloatornull",
    "tobooleanornull",
    "tolower",
    "toupper",
    "trim",
    "ltrim",
    "rtrim",
    "substring",
    "replace",
    "split",
    "left",
    "right",
    "reverse",
    "abs",
    "ceil",
    "floor",
    "round",
    "sign",
    "sqrt",
    "exp",
    "log",
    "log10",
    "e",
    "pi",
    "sin",
    "cos",
    "tan",
    "cot",
    "asin",
    "acos",
    "atan",
    "atan2",
    "degrees",
    "radians",
    "haversin",
    "date",
    "datetime",
    "localdatetime",
    "timestamp",
    "nodes",
    "relationships",
    "length",
    "exists",
    "isempty",
    "char_length",
    "character_length",
    "rand",
    "randomuuid",
    "nullif",
    "date.truncate",
    "datetime.truncate",
    "date.statement",
    "datetime.statement",
    "date.transaction",
    "datetime.transaction",
    "date.realtime",
    "datetime.realtime",
    "localdatetime.statement",
    "localdatetime.transaction",
    "localdatetime.realtime",
    "datetime.fromepoch",
    "datetime.fromepochmillis",
    "localdatetime.truncate",
    "isnan",
];

/// True for an aggregate function.
pub fn is_aggregate(name: &str) -> bool {
    AGGREGATES.contains(&name.to_ascii_lowercase().as_str())
}

/// True for an implemented function (scalar or aggregate).
pub fn is_known(name: &str) -> bool {
    let l = name.to_ascii_lowercase();
    SCALARS.contains(&l.as_str()) || AGGREGATES.contains(&l.as_str())
}
